name: lucasg
highlighter: rouge
markdown: kramdown

# Permalinks
permalink:        pretty

# Setup
title:            lucasg.github.io
tagline:          blog
paginate:         1
url:          	  https://lucasg.github.io
baseurl:          https://lucasg.github.io/
author:
  name:           lucasg
  email:          lucas.georges@outlook.com


# to recreate the "site.github" locally
repository: lucasg/lucasg.github.io

excerpt_separator: <!--more-->

collections:
  resources:
    sort_by: date

# gems
plugins:
  - jekyll-feed
  - jemoji
  - jekyll-github-metadata
