name: lucasg
highlighter: rouge
markdown: kramdown

# Permalinks
permalink:        pretty

# Setup
title:            lucasg.github.io
tagline:          blog
paginate:         1
url:          	  http://lucasg.github.io
baseurl:          http://lucasg.github.io/
author:
  name:           lucasg
  email:          lucas.georges@outlook.com
  github:         https://github.com/lucasg

# Custom vars
version:          1.0.0
github:		  [Repository metadata]

excerpt_separator: <!--more-->

# gems
gems:
  - jekyll-feed
  - jemoji
