name: lucasg
highlighter: pygments
markdown: kramdown

# Permalinks
permalink:        pretty

# Setup
title:            lucasg.github.io
tagline:          blog
paginate:         1
url:          	  http://lucasg.github.io
baseurl:         /
author:
  name:           lucasg
  email:          lucasg@outlook.com

# Custom vars
version:          1.0.0
github:		  [Repository metadata]

excerpt_separator: <!--more-->
